query getFields {
  __MODEL_COLLECTION__(order: sys_id_ASC) {
    total
    items {
      ...SystemProperty
    }
  }
}

fragment SystemProperty on Entry {
  sys {
    id
    publishedAt
    publishedVersion
  }
}
