name: Check on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Lint, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
      - name: Check node and npm version
        run: node -v && npm -v
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint:strict
      - name: Build
        run: CI=true npm run-script build:preview
      - name: Google Chat Notification
        uses: envlop/google-chat-notification@releases/v1
        if: always()
        with:
          name: 'PR is opened or updated'
          url: 'https://chat.googleapis.com/v1/spaces/AAAAzi4n8fY/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=lelUAHui9AS_LvnQ298F44crG74vdHLZwUoZDPFv1hY%3D'
          status: ${{ job.status }}
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: deploystep
        with:
          channelId: "${{ github.head_ref }}"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GCP_SA_KEY }}"
          expires: 7d
          projectId: envlop-project-staging
