# See `https://medium.com/sliit-foss/deploy-a-react-app-into-firebase-hosting-with-github-actions-d0cc1e6861b0`

name: Build and Deploy to Firebase (Production)

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+*'] # ex. v1.9.29

jobs:
  build:
    name: Build source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
      - name: Install Dependencies
        run: npm install
      - name: Check linter
        run: npm run lint:strict
      - name: Build As Usual
        run: CI=true npm run-script build:prod
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    name: Deploy to firebase hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy To Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P product --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: envlop-project-product

      - name: Google Chat Notification
        uses: envlop/google-chat-notification@releases/v1
        if: always()
        with:
          name: 'フロントアプリの本番環境へのデプロイ'
          url: 'https://chat.googleapis.com/v1/spaces/AAAAzi4n8fY/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=lelUAHui9AS_LvnQ298F44crG74vdHLZwUoZDPFv1hY%3D'
          status: ${{ job.status }}
          # token: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN is automatically created in workflow

      #- name: Use Slack Notification
      #  uses: homoluctus/slatify@master
      #  if: always()
      #  with:
      #    type: ${{ job.status }}
      #    job_name: '本番環境へのデプロイ'
      #    icon_emoji: ':react:'
      #    #username: 'daichi_komatsu'
      #    channel: '#gift_bot'
      #    url: ${{ secrets.SLACK_WEBHOOK }}
      #    #commit: true
      #    token: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is automatically created in workflow
